// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdkppuqkswzojwqxdqzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpka3BwdXFrc3d6b2p3cXhkcXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTU3NDcsImV4cCI6MjA3MTE3MTc0N30.3YjK7yBa2ZH7xwG0JaYtplv18B6g5cR4QyNQif8AYjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});